# -*- coding: utf-8 -*-
"""Copia di Untitled1.ipynb
#hello hi hello
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wTC3x8Kq2NcCpU3m3mxRcq_fqmcctplz

1) THESE STEPS ARE FOR SETTING UP FOR THE SUCCESSIVE POINTS
"""

!pip install -U spacy

!python -m spacy download en

"""1.1) DATA CLEANING

1.1.1) IMPORTING THE DATASET
"""

# IMPORTING DRIVE
from google.colab import drive
drive.mount('/content/drive')

# SETTING DIRECTORY
import os

directory_path = '/content/drive/MyDrive/Progetto Data vis. and Text mining'
os.chdir(directory_path)

print(os.listdir())  # Elenca i file nella directory corrente

# IMPORTING THE FILES

def read_iob2_file(filename):
    with open(filename, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
    return content


file1 = read_iob2_file('file1.ann')
file2 = read_iob2_file('file2.ann')

print("Contenuto di file1:")
print(file1)

print("\nContenuto di file2:")
print(file2)

"""1.1.2) NON LATIN CHARACTERS AND NA ELIMINATION

"""

import re
import os

def pulisci_file(input_filename, output_filename):

    # Legge tutte le righe dal file di input
    with open(input_filename, 'r', encoding='utf-8') as file:
        lines = file.readlines()

    # Filtra le righe che non contengono caratteri arabi e non sono vuote o NA
    filtered_lines = [
        line for line in lines
        if line.strip() and not re.search(r'[\u0600-\u06FF]', line)  # Rimuove righe vuote e con caratteri arabi
    ]

    # Scrive le righe filtrate nel file di output
    with open(output_filename, 'w', encoding='utf-8') as file:
        file.writelines(filtered_lines)

# Pulisci i file
pulisci_file('file1.ann', 'file1_clean')  # Pulisce file1
pulisci_file('file2.ann', 'file2_clean')  # Pulisce file2

file1
